language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
env:
  - HTMLLIB5TESTS=$PWD/html5lib-tests-master/ LOGLEVEL=INFO
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm"* ]]; then cat hhvm-php7.ini >> /etc/hhvm/php.ini; fi
install:
  - wget -O- https://github.com/html5lib/html5lib-tests/archive/master.tar.gz | tar -zxv
  - composer install --ignore-platform-reqs